version: '3'

networks:
  mynet:
    driver: bridge

services:
  test:
    image: curlimages/curl:7.77.0
    networks:
      - mynet
    hostname: test
    entrypoint: /test/test-script.sh
    volumes:
        - ./single_auth_request.sh:/test/single_auth_request.sh
        - ./test-script.sh:/test/test-script.sh
    depends_on:
      keycloak:
        condition: service_healthy    
      
  mysql:
      image: mysql:5.7
      networks:
      - mynet
      environment:
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
        
  keycloak:
      image: jboss/keycloak:15.1.1
      networks:
      - mynet
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        KEYCLOAK_STATISTICS: all
        KEYCLOAK_IMPORT: /opt/jboss/tools/testRealm.json
      entrypoint: /opt/jboss/tools/extended-docker-entrypoint.sh
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9990"]        
        interval: 30s
        timeout: 5s
        retries: 5
      ports:
        - 8481:8080
        - 9991:9990
        - 8787:8787
      volumes:
        - ./keycloak/docker-entrypoint.sh:/opt/jboss/tools/extended-docker-entrypoint.sh
 #       - ./keycloak/configure-caches.cli:/opt/jboss/startup-scripts/configure-caches.cli        
 #      - ./keycloak/configure-cache-owners.cli:/opt/jboss/startup-scripts/configure-cache-owners.cli        
        - ./keycloak/configure-logging.cli:/opt/jboss/startup-scripts/configure-logging.cli        
 #       - ./keycloak/configure-cache-lifespan.cli:/opt/jboss/startup-scripts/configure-cache-lifespan.cli
        - ./keycloak/testRealm.json:/opt/jboss/tools/testRealm.json    
        - ./jmx-client:/copy
      depends_on:
        - mysql
        
